name: Deploy React Vite to GitHub Pages

on:
  push:
    branches:
      - production  # Chạy action khi có thay đổi trên nhánh production
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  deploy:

    steps:
      # Checkout mã nguồn của dự án
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Cài đặt Node.js phiên bản 18

      # Cài đặt các phụ thuộc của dự án
      - name: Install dependencies
        run: npm install

      # Build ứng dụng React + Vite
      - name: Build project
        run: npm run build  # Lệnh build của Vite sẽ tạo ra thư mục ./dist

      # Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Dùng GITHUB_TOKEN mặc định
          publish_dir: ./dist  # Chỉ định thư mục chứa các tệp build
          branch: gh-pages  # Nhánh để deploy (có thể thay đổi theo nhu cầu)